# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dupa', '0002_paragon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragon',
            old_name='file1',
            new_name='image',
        ),
    ]
