# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dupa', '0004_paragon_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='item_name',
            field=models.CharField(blank=True, default='Processing image... Refresh to check for results.', max_length=120, null=True),
        ),
    ]
