# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dupa', '0005_auto_20170114_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParagonItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paragonu', models.IntegerField(blank=True, null=True)),
                ('cena', models.CharField(blank=True, max_length=120, null=True)),
                ('produkt', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
