# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dupa', '0006_paragonitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragon',
            name='image_data',
            field=models.TextField(blank=True, default='Processing image... Refresh to check for results. If that doesnt help please wait or do something else one the website', null=True),
        ),
        migrations.AlterField(
            model_name='paragonitems',
            name='id_paragonu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dupa.Paragon'),
        ),
    ]
