# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
