# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0002_auto_20170110_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ip_address',
            field=models.CharField(default='ABV', max_length=120),
            preserve_default=False,
        ),
    ]
