# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0003_join_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='dupa',
            field=models.CharField(default='dupa', max_length=120),
        ),
    ]
