# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0004_join_dupa'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='kupa',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
