# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0005_join_kupa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='kupa',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
