# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0006_auto_20170111_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='dupa',
        ),
        migrations.RemoveField(
            model_name='join',
            name='kupa',
        ),
        migrations.AlterField(
            model_name='join',
            name='ip_address',
            field=models.CharField(default='ABC', max_length=120),
        ),
    ]
