# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0007_auto_20170111_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ref_if',
            field=models.CharField(default='abra', max_length=120),
        ),
    ]
