# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0009_auto_20170111_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinFirends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Sharer', to='joins.Join')),
                ('friends', models.ManyToManyField(blank=True, null=True, related_name='Friend', to='joins.Join')),
            ],
        ),
    ]
